import type { Metadata } from "next";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";

const Kumbh = Kumbh_Sans({
  variable: "--font-Kumbh_Sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "welcome | FutureTech",
    template: "%S | FutureTech",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Kumbh.variable}  antialiased bg-zinc-950`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
